import { AppLink } from "../navigation";

export function PrivacyPage() {
  return <article className="editorial-page about-page legal-page">
    <p className="section-label">Politica de Privacidad</p>
    <h1>Tu informacion, tratada con claridad.</h1>
    <p>Vigente desde el 31 de agosto de 2026.</p>
    <h2>Responsable</h2>
    <p>Marcelo Gabriel Gonzalez, en el partido de Gral San Martin, Provincia de Buenos Aires. Consultas: <a href="mailto:bookia.app.admin@gmail.com">bookia.app.admin@gmail.com</a>.</p>
    <h2>Datos y finalidades</h2>
    <p>Tratamos datos de cuenta, perfil, rasgos lectores declarados, libros buscados, libros guardados, librerias seguidas, estado de autor y registro de su declaracion, titulos, sinopsis, genero, editorial, ano y portadas de obras propias, incluido su celular con WhatsApp opcional, datos de librerias -incluido el celular con WhatsApp-, catalogos, imagenes, sesiones, suscripciones -incluido el correo de la cuenta pagadora de Mercado Pago-, datos de acceso con Google -identificador, correo verificado y, para altas de lectores, nombre- y metricas seudonimizadas y agregadas de interaccion publica para prestar Bookia, proteger la plataforma, brindar soporte, administrar planes y cobros, mostrar estadisticas agregadas a las librerias y, con consentimiento separado, enviar novedades y promociones.</p>
    <p>Las personas anfitrionas pueden cargar portadas de clubes de lectura; las conservamos en la infraestructura de Bookia mientras exista el club o hasta que se eliminen.</p>
    <p>Si una persona expresa interés en anotarse a un club de lectura, debe usar una cuenta autenticada. Tratamos su nombre, correo electrónico, teléfono y la fecha de aceptación de esta política para comunicarlos únicamente al anfitrión de ese club. El anfitrión accede a esos datos desde su panel de Bookia para contactar a la persona; no los usamos para novedades o promociones. Eliminamos estas solicitudes de forma automática a los 12 meses.</p>
    <h2>Notificaciones en Android</h2>
    <p>Si las activás voluntariamente en la app Android, tratamos un token de dispositivo generado por Firebase Cloud Messaging, su plataforma, estado de activación y última fecha de uso. Lo vinculamos con tu cuenta para enviar avisos sobre libros, disponibilidad e interacciones relevantes. El token se guarda cifrado y su hash se usa para reconocerlo sin exponerlo.</p>
    <p>Podés desactivar las notificaciones desde Bookia o desde los ajustes de Android sin perder ninguna otra función. Los tokens desactivados dejan de recibir envíos; también deshabilitamos los que Firebase informa como inválidos y los eliminamos ante una solicitud válida de supresión. La retención acompaña la vigencia de la cuenta y las necesidades técnicas y de seguridad del servicio.</p>
    <h2>Integracion con Tiendanube</h2>
    <p>Cuando una libreria conecta voluntariamente su tienda, tratamos el identificador de la tienda, un token de acceso cifrado y datos de productos necesarios para importar el catalogo: identificadores, titulo, descripcion, variantes, precio, moneda, stock, disponibilidad, imagen, enlace publico y el payload de origen. El acceso solicitado es de solo lectura de productos. El token se conserva cifrado y no se muestra en respuestas ni registros. Al desconectar desde Bookia eliminamos la conexion y el token, pero conservamos el catalogo ya importado hasta que la libreria lo edite o elimine.</p>
    <p>Si Tiendanube envia una solicitud de privacidad <strong>store/redact</strong> con firma valida, eliminamos definitivamente la conexion y los productos importados de esa tienda, junto con sus imagenes almacenadas por Bookia. Bookia no solicita ni conserva datos de clientes o pedidos de Tiendanube; sus solicitudes de eliminacion o acceso se validan y se responden sin incorporar esos datos a Bookia.</p>
    <h2>Integracion con Google Sheets</h2>
    <p>Cuando una libreria conecta voluntariamente una planilla, Bookia solicita acceso de solo lectura a sus hojas de calculo y trata el identificador de la planilla, un token de actualizacion cifrado y los campos del catalogo incluidos en la pestaña Catalogo: codigo, titulo, autor, editorial, idioma, descripcion, estado, precio, moneda, stock, disponibilidad y enlaces de compra o imagen. El token se conserva cifrado en el backend, no se muestra en respuestas ni registros y se elimina al desconectar la integracion.</p>
    <p>La libreria puede iniciar una sincronizacion manual y Bookia realiza una sincronizacion semanal los domingos a las 03:00, hora argentina. Si una fila deja de estar en la planilla durante una lectura completa y valida, el libro queda oculto sin eliminar sus datos enriquecidos; si la fila reaparece, vuelve a publicarse. Una lectura fallida o una planilla invalida no modifica el catalogo anterior. Al desconectar Google Sheets se conserva el catalogo importado y dejan de realizarse nuevas sincronizaciones.</p>
    <h2>Perfiles de autor</h2>
    <p>Cuando una persona activa la capacidad de autor, conservamos si esta activa, la version de la declaracion de derechos aceptada y la fecha de aceptacion. Tambien almacenamos hasta cinco libros propios y sus portadas en infraestructura de Bookia. La persona puede cargar o eliminar voluntariamente un celular con WhatsApp para consultas sobre sus obras; ese número se comparte únicamente con cuentas autenticadas y deja de estar disponible si desactiva su perfil de autor. La condicion Autor/a en Bookia se muestra solamente mientras la capacidad esta activa y el perfil lector es publico. La desactivacion oculta la insignia; los libros propios y sus portadas se conservan junto con el teléfono para una eventual reactivacion, junto con el registro de aceptacion, mientras exista la cuenta. Cada libro puede eliminarse definitivamente desde el panel. La eliminacion de la cuenta aplica las reglas generales de supresion indicadas en esta politica.</p>
    <h2>Acceso con Google</h2>
    <p>Si elegis acceder o registrarte con Google, usamos esos datos exclusivamente para autenticar, crear o vincular tu cuenta de Bookia. Bookia no persiste tokens de Google ni usa los datos recibidos de Google para publicidad o venta a terceros.</p>
    <h2>Seguimientos y estadisticas</h2>
    <p>Cuando una persona lectora sigue o deja de seguir una libreria, Bookia conserva la relacion activa y el historial de esas acciones mientras exista su cuenta. Usamos ese historial para calcular cantidades y variaciones por periodo. Las librerias reciben exclusivamente estadisticas agregadas: no acceden por esta funcion al nombre, perfil, correo ni otros datos personales de quienes las siguen. Los eventos del embudo de registro y seguimiento son datos agregados y no constituyen prueba de una operacion comercial entre una persona y una libreria.</p>
    <h2>Informacion publica</h2>
    <p>El contacto digital de una libreria, incluido su celular con WhatsApp, se muestra exclusivamente a una cuenta autenticada en todas las superficies de descubrimiento, incluidos perfiles de librerias, carruseles, resultados de busqueda y detalle de libros. El celular con WhatsApp que agregan voluntariamente las personas autoras también se revela únicamente a cuentas autenticadas desde el detalle de sus obras. La direccion fisica puede seguir visible a visitantes. Los perfiles lectores son publicos y muestran el nombre, alias, biografia, los generos de lectura seleccionados, los rasgos del Pasaporte lector, hasta dos enlaces externos que agregue voluntariamente, la lista de libros que declara estar buscando y, si corresponde, su condicion activa de autor. La persona puede editar o eliminar esos datos en cualquier momento. El correo, credenciales, sesiones, libros guardados como favoritos, librerias seguidas y datos de facturacion nunca se publican.</p>
    <h2>Proveedores</h2>
    <p>Usamos Google para acceso y registro opcional, para leer catalogos de Google Sheets cuando una libreria conecta una planilla y Firebase Cloud Messaging para entregar notificaciones Android; Railway y PostgreSQL para infraestructura, Railway Buckets/Tigris para imagenes, Resend para correos transaccionales y recuperacion de cuentas, Mercado Pago para autorizar y cobrar suscripciones, Tiendanube para importar catalogos conectados, OpenAI para funciones de autocompletado de catalogo y Telegram para el bot. Estos proveedores pueden procesar datos fuera de Argentina cuando sea necesario para prestar el servicio.</p>
    <h2>Cookies y pagos</h2>
    <p>Usamos cookies tecnicas de sesion y seguridad (CSRF). Medimos interacciones publicas basicas, como aperturas de libros, visitas a librerias y clicks de contacto, sin instalar cookies de analitica. Para proteger los eventos publicos contra abuso, aplicamos limitacion de frecuencia respaldada por la base de datos mediante un HMAC seudonimizado de la direccion IP. Los buckets seudonimizados que superan los 30 dias se eliminan de forma oportunista cuando vuelve a ejecutarse un control del mismo tipo; si no hay nuevo trafico de ese tipo, pueden persistir por mas tiempo hasta esa limpieza o una solicitud valida de supresion. Consulta la <AppLink href="/cookies">Politica de Cookies</AppLink>. Mercado Pago procesa el medio de pago; Bookia conserva el correo de la cuenta pagadora, identificadores de suscripcion, importes, estados, fechas y eventos necesarios para administrar el servicio, pero no almacena los datos completos de tarjetas.</p>
    <h2>Conservacion, derechos y menores</h2>
    <p>Conservamos datos mientras sean necesarios para el servicio. Los seguimientos y su historial, los rasgos lectores, los libros buscados y el perfil de autor se eliminan con la cuenta de la persona lectora. Tras una solicitud validada, borramos o anonimizamos datos no necesarios en hasta 30 dias, salvo copias de seguridad, seguridad, registros de facturacion u obligaciones legales. Podes solicitar acceso, rectificacion o supresion por correo; tambien podes reclamar ante la AAIP. Bookia es para mayores de 13 anos; menores requieren autorizacion de madre, padre o tutor.</p>
    <h2>Newsletter y cambios</h2>
    <p>El newsletter es opcional y puede darse de baja en cualquier momento. Actualizaremos esta politica si cambian los tratamientos o proveedores.</p>
    <p>El uso de Bookia tambien se rige por los <AppLink href="/terms">Terminos y Condiciones</AppLink>.</p>
    <p><AppLink href="/register">Crear una cuenta</AppLink></p>
  </article>;
}
