import { getAuthorProfileView } from "../authorProfileState";
import { AuthorBooksManager } from "./AuthorBooksManager";

const RIGHTS_DECLARATION = "Declaro que soy autor/a o que cuento con autorización suficiente para publicar en Bookia las obras que incorpore, y acepto ser responsable por la veracidad y los derechos del contenido.";

export function AuthorProfileSection({ authorProfile, genres = [], accepted, onAcceptedChange, onActivate, onDeactivate, onSaveWhatsApp, whatsappPhone = "", onWhatsAppPhoneChange, pending, feedback }) {
  const view = getAuthorProfileView({ authorProfile });
  if (view === "inactive") {
    return <section className="reader-profile-tab-panel author-profile-panel" aria-labelledby="author-profile-title"><div className="dashboard-card author-profile-card"><p className="section-label">AUTORES EN BOOKIA</p><h2 id="author-profile-title">Publicá tus libros en Bookia</h2><p>Activá gratis tu perfil de autor/a. Tu nombre, alias y biografía serán los mismos que ya usás en tu perfil lector.</p><form onSubmit={onActivate}><label className="author-rights-declaration" htmlFor="rights-declaration"><input id="rights-declaration" type="checkbox" checked={accepted} onChange={(event) => onAcceptedChange(event.target.checked)} required disabled={pending} /><span>{RIGHTS_DECLARATION}</span></label><button className="primary-button" type="submit" disabled={pending || !accepted}>{pending ? "Activando..." : "Activar perfil de autor/a"}</button></form>{feedback ? <p className="feedback" role="status">{feedback}</p> : null}</div></section>;
  }
  return <section className="reader-profile-tab-panel author-profile-panel" aria-labelledby="author-profile-title"><div className="dashboard-card author-profile-card is-active"><p className="section-label">AUTORES EN BOOKIA</p><h2 id="author-profile-title">Tu perfil de autor/a está activo</h2><p>Tu perfil público ya muestra la insignia Autor/a en Bookia.</p></div><AuthorBooksManager genres={genres} /><div className="dashboard-card author-profile-settings"><div><p className="section-label">CONFIGURACIÓN</p><h3>Perfil de autor/a</h3><p>Si lo desactivás, conservaremos tus libros y podrás volver a administrarlos cuando lo reactives.</p></div><form onSubmit={onSaveWhatsApp}><label><span>Celular con WhatsApp <small>(opcional)</small></span><input type="tel" value={whatsappPhone} onChange={(event) => onWhatsAppPhoneChange?.(event.target.value)} maxLength={50} placeholder="11 2222-3333" disabled={pending} /><small>Solo se comparte con cuentas que hayan iniciado sesión.</small></label><button className="secondary-button" type="submit" disabled={pending}>{pending ? "Guardando..." : "Guardar WhatsApp"}</button></form><button className="secondary-button" type="button" onClick={onDeactivate} disabled={pending}>{pending ? "Desactivando..." : "Desactivar perfil"}</button>{feedback ? <p className="feedback" role="status">{feedback}</p> : null}</div></section>;
}
