import { getAuthorProfileView } from "../authorProfileState";

const RIGHTS_DECLARATION = "Declaro que soy autor/a o que cuento con autorización suficiente para publicar en Bookia las obras que incorpore, y acepto ser responsable por la veracidad y los derechos del contenido.";

export function AuthorProfileSection({ authorProfile, readerProfile, accepted, onAcceptedChange, onActivate, onDeactivate, pending, feedback }) {
  const view = getAuthorProfileView({ authorProfile, readerProfile });
  if (view === "inactive") {
    return <section className="reader-profile-tab-panel author-profile-panel" aria-labelledby="author-profile-title"><div className="dashboard-card author-profile-card"><p className="section-label">AUTORES EN BOOKIA</p><h2 id="author-profile-title">Publicá tus libros en Bookia</h2><p>Activá gratis tu perfil de autor/a. Tu nombre, alias y biografía serán los mismos que ya usás en tu perfil lector.</p><form onSubmit={onActivate}><label className="author-rights-declaration" htmlFor="rights-declaration"><input id="rights-declaration" type="checkbox" checked={accepted} onChange={(event) => onAcceptedChange(event.target.checked)} required disabled={pending} /><span>{RIGHTS_DECLARATION}</span></label><button className="primary-button" type="submit" disabled={pending || !accepted}>{pending ? "Activando..." : "Activar perfil de autor/a"}</button></form>{feedback ? <p className="feedback" role="status">{feedback}</p> : null}</div></section>;
  }
  return <section className="reader-profile-tab-panel author-profile-panel" aria-labelledby="author-profile-title"><div className="dashboard-card author-profile-card is-active"><p className="section-label">AUTORES EN BOOKIA</p><h2 id="author-profile-title">Tu perfil de autor/a está activo</h2><p>{view === "active_public" ? "Tu perfil público ya muestra la insignia Autor/a en Bookia." : "La insignia Autor/a en Bookia aparecerá cuando publiques tu perfil lector."}</p><p>En el próximo paso podrás cargar y presentar tus propios libros.</p><button className="secondary-button" type="button" onClick={onDeactivate} disabled={pending}>{pending ? "Desactivando..." : "Desactivar perfil"}</button>{feedback ? <p className="feedback" role="status">{feedback}</p> : null}</div></section>;
}
